locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py
spawn-rate = 1
run-time = 3m
headless = true
users = 45
html = ./scenarios/http/gateway/existing_user_get_operations/report.html
processes = 4