locustfile = ./scenarios/http/gateway/new_user_issue_physical_card/scenario.py
spawn-rate = 0.5
run-time = 3m
headless = true
users = 24
html = ./scenarios/http/gateway/new_user_issue_physical_card/report_2.html