locustfile = ./scenarios/grpc/gateway/existing_user_issue_virtual_card/scenario.py
spawn-rate = 1
run-time = 3m
headless = true
users = 60
html = ./scenarios/grpc/gateway/existing_user_issue_virtual_card/report.html